### ISSUE TITLE
Can it have OSx like titlebar in a cross-platform way?

### ISSUE THREAD

**Issue by Baldrs** [twostairs/loop#2]
![electron](https://cloud.githubusercontent.com/assets/814651/12536163/d5a04efe-c29c-11e5-9ca9-268198cbc107.png)

**Comment by Baldrs** [comment]
https://github.com/atom/electron/blob/master/docs/api/frameless-window.md

Need to add custom css into content area

**Comment by Baldrs** [comment]
SOOO, that's easy, will file pull request

**Comment by mrusme** [comment]
Apparently you solved the issue yourself, didn't you @Baldrs?
